spring:

  application:
    name: cards

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${CARDS_DB_HOST:localhost}:${CARDS_DB_PORT:5432}/cards_db
    username: ${CARDS_DB_USER:dev}
    password: ${CARDS_DB_USER:pass}

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/schema-migration

server:
  port: 9000

app:
  version: @project.version@
  name: @artifactId@
  description: @description@
