spring:
  application:
    name: app-manager

  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/microservices

server:
  port: 8071
