spring:
  application:
    name: app-manager

  profiles:
    active: git

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/microservices
        git:
          uri: https://github.com/oleh-kuzmenko/microservices-configs.git
          clone-on-start: true
          force-pull: true
          default-label: main
          timeout: 10

server:
  port: 8071

encrypt:
  key: Srk1mfEGpcGT7FVchkNROwMDXrWAysku0Nll2WhWHvcadreH6rdjlVD1r8B70Mfp

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
