spring:
  application:
    name: gateway

  config:
    import:
      - optional:configserver:${CONFIG_SERVER_URI:http://localhost:8071}
      - classpath:routing.yml

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted

  info:
    env:
      enabled: true
