spring:
  application:
    name: gateway

  config:
    import:
      - optional:configserver:${CONFIG_SERVER_URI:http://localhost:8071}
      - classpath:routing.yml

  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 1000
            response-timeout: 25s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted

  info:
    env:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      accountCircuitBreaker:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 10000
