spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: accounts-service
              uri: lb://ACCOUNTS
              predicates:
                - Path=/api/v1/accounts/**, /api/v1/customers/**
            - id: loans-service
              uri: lb://LOANS
              predicates:
                - Path=/api/v1/loans/**
            - id: cards-service
              uri: lb://CARDS
              predicates:
                - Path=/api/v1/cards/**
