spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: accounts-service
              uri: lb://ACCOUNTS
              predicates:
                - Path=/api/v1/accounts/**, /api/v1/customers/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: accountCircuitBreaker
                    fallbackUri: forward:/fallback
            - id: loans-service
              uri: lb://LOANS
              predicates:
                - Path=/api/v1/loans/**
              filters:
                - name: Retry
                  args:
                    retries: 5
                    delay: 1s
                    max-retry-duration: 10s
                    backoff:
                      first-backoff: 1s
                      max-backoff: 10s
                      factor: 2
                    statuses: BAD_GATEWAY, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT, INTERNAL_SERVER_ERROR
                    methods: GET
            - id: cards-service
              uri: lb://CARDS
              predicates:
                - Path=/api/v1/cards/**
