spring:

  application:
    name: accounts

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${ACCOUNTS_DB_HOST:localhost}:${ACCOUNTS_DB_PORT:5432}/accounts_db
    username: ${ACCOUNTS_DB_USER:dev}
    password: ${ACCOUNTS_DB_USER:pass}

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/schema-migration

  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8071}

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

app:
  version: @project.version@
  name: @artifactId@
  description: @description@

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    shutdown:
      access: unrestricted

  info:
    env:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${SERVICE_REGISTRY_UTI:http://localhost:8070/eureka}
    fetch-registry: true
    register-with-eureka: true

info:
    app:
        name: @artifactId@
        description: @description@
        version: @project.version@
    build:
        name: @artifactId@
        version: @project.version@

logging:
  level:
    org.springframework.web: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      CardsClientgetCardString:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 10000
      LoansClientgetLoanString:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 10000
