spring:

  application:
    name: accounts

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${ACCOUNTS_DB_HOST:localhost}:${ACCOUNTS_DB_PORT:5432}/accounts_db
    username: ${ACCOUNTS_DB_USER:dev}
    password: ${ACCOUNTS_DB_USER:pass}

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/schema-migration

  profiles:
    active:
      - h2

  config:
    import: configserver:http://localhost:8071

app:
  version: @project.version@
  name: @artifactId@
  description: @description@
