version: '3.9'

services:

  app-manager:
    image: app-manager:0.0.1
    container_name: app-manager
    healthcheck:
      test: "curl -f http://localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - 8071:8071
    networks:
      microservices:
    deploy:
      resources:
        limits:
          memory: 700M

  service-registry:
    image: service-registry:0.0.1
    container_name: service-registry
    healthcheck:
      test: "curl -f http://localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - 8070:8070
    environment:
      - CONFIG_SERVER_URI=http://app-manager:8071
    depends_on:
      app-manager:
        condition: service_healthy
    networks:
      microservices:
    deploy:
      resources:
        limits:
          memory: 700M

  gateway:
    image: gateway:0.0.1
    container_name: gateway
    ports:
      - 8072:8072
    environment:
      - CONFIG_SERVER_URI=http://app-manager:8071
      - SERVICE_REGISTRY_UTI=http://service-registry:8070/eureka
    depends_on:
      service-registry:
        condition: service_healthy
    networks:
      microservices:
    deploy:
      resources:
        limits:
          memory: 700M

  accounts:
    image: accounts:0.0.1
    container_name: accounts
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=h2
      - CONFIG_SERVER_URI=http://app-manager:8071
      - SERVICE_REGISTRY_UTI=http://service-registry:8070/eureka
    depends_on:
      service-registry:
        condition: service_healthy
    networks:
      microservices:
    deploy:
      resources:
        limits:
          memory: 700M

  loans:
    image: loans:0.0.1
    container_name: loans
    ports:
      - 8090:8090
    environment:
      - SPRING_PROFILES_ACTIVE=h2
      - CONFIG_SERVER_URI=http://app-manager:8071
      - SERVICE_REGISTRY_UTI=http://service-registry:8070/eureka
    depends_on:
      service-registry:
        condition: service_healthy
    networks:
      microservices:
    deploy:
      resources:
        limits:
          memory: 700M

  cards:
    image: cards:0.0.1
    container_name: cards
    ports:
      - 9000:9000
    environment:
      - SPRING_PROFILES_ACTIVE=h2
      - CONFIG_SERVER_URI=http://app-manager:8071
      - SERVICE_REGISTRY_UTI=http://service-registry:8070/eureka
    depends_on:
      service-registry:
        condition: service_healthy
    networks:
      microservices:
    deploy:
      resources:
        limits:
          memory: 700M

networks:
  microservices:
    driver: bridge
